### ISSUE TITLE
Adding a 'select all expansions' button

### ISSUE THREAD

**Issue by texasjusticar** [TomTomKinch/Marvel-Legendary-Randomizer#1]
Been using your randomizer online since the ios app I previously used keeps crashing.  Generally happy with it, but a quality of life improvement if you don't mind would be to add a 'Select all Expansions' button.  I own all of them.  And checking all the boxes when setting up another game is kinda tedious :-)

Appreciate the work.

**Comment by TomTomKinch** [comment]
I get it being tedious :P. Added a Select All button. Minimal testing done on it, but it seems to be behaving correctly.
